framework:
    secret: '%env(APP_SECRET)%'
    default_locale: en
    enabled_locales: ['en', 'pl']
    
    http_client:
        default_options:
            timeout: 30
            max_redirects: 5

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    http_method_override: false
    handle_all_throwables: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

when@prod:
    framework:
        http_client:
            default_options:
                timeout: 60